//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPDASHBOARDTABLE
    {
        public decimal IID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUMMARY { get; set; }
        public string CATEGORY { get; set; }
        public string STATUS { get; set; }
        public string APPROVED { get; set; }
        public string PRIORITY { get; set; }
        public string REQUESTOR { get; set; }
        public string REQUEST_DEPARTMENT { get; set; }
        public string SPONSOR { get; set; }
        public string PUSHING_PROJECT { get; set; }
        public string IT_OWNER { get; set; }
        public string IT_DIVISION { get; set; }
        public Nullable<System.DateTime> PUSH_DATE { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
    }
}
